apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: jetzeluyten
  labels:
    dev.okteto.com/deployed-by: enterprisebackend
    stack.okteto.com/name: enterprisebackend
    stack.okteto.com/service: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      stack.okteto.com/name: enterprisebackend
      stack.okteto.com/service: api-gateway
  template:
    metadata:
      labels:
        dev.okteto.com/deployed-by: enterprisebackend
        stack.okteto.com/name: enterprisebackend
        stack.okteto.com/service: api-gateway
    spec:
      containers:
      - env:
        - name: DISH_SERVICE_BASEURL
          value: dish-service:8081
        - name: TABLE_SERVICE_BASEURL
          value: table-service:8082
        - name: VISIT_SERVICE_BASEURL
          value: visit-service:8080
        - name: WAITER_SERVICE_BASEURL
          value: waiter-service:8083
        image: jetzel/api-gateway
        imagePullPolicy: Always
        name: api-gateway
        ports:
        - containerPort: 8084
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 0
