apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\eigenaar\Documents\kompose.exe convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-gateway
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\eigenaar\Documents\kompose.exe convert
        kompose.service.type: LoadBalancer
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: api-gateway
    spec:
      containers:
        - env:
            - name: DISH_SERVICE_BASEURL
              value: dish-service:8082
            - name: TABLE_SERVICE_BASEURL
              value: table-service:8080
            - name: VISIT_SERVICE_BASEURL
              value: visit-service:8081
            - name: WAITER_SERVICE_BASEURL
              value: waiter-service:8083
          image: jetzel/api-gateway
          name: api-gateway
          ports:
            - containerPort: 8084
          resources: {}
      restartPolicy: Always
status: {}
