apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\eigenaar\Documents\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: dish-service
  name: dish-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dish-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\eigenaar\Documents\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: dish-service
    spec:
      containers:
        - env:
            - name: MONGODB_HOST
              value: mongo-dish
            - name: MONGODB_PORT
              value: "27019"
          image: jetzel/dish-service
          name: dish-service
          ports:
            - containerPort: 27019
          resources: {}
      restartPolicy: Always
status: {}
