apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\eigenaar\Documents\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: dish-service
  name: dish-service
spec:
  ports:
    - name: "27019"
      port: 27019
      targetPort: 27019
  selector:
    io.kompose.service: dish-service
status:
  loadBalancer: {}
