apiVersion: v1
kind: Service
metadata:
  name: mongo-table
spec:
  selector:
    app: mongo-table
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-table
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-table
  template:
    metadata:
      labels:
        app: mongo-table
    spec:
      containers:
        - name: mongo-table
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-table-data
              mountPath: /data/db
---
# Repeat the above pattern for mongo-dish, mongo-waiter, and mysql-visit services.

apiVersion: v1
kind: Service
metadata:
  name: table-service
spec:
  selector:
    app: table-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: table-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: table-service
  template:
    metadata:
      labels:
        app: table-service
    spec:
      containers:
        - name: table-service
          image: jetzel/table-service
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_HOST
              value: mongo-table
---
# Repeat the above pattern for dish-service, waiter-service, visit-service, and api-gateway services.
