apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\eigenaar\Documents\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-table
  name: mongo-table
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo-table
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\eigenaar\Documents\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: mongo-table
    spec:
      containers:
        - image: mongo:latest
          name: mongo-table
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-table-data
            - mountPath: /data/configdb
              name: mongo-table-data-config
      restartPolicy: Always
      volumes:
        - name: mongodb-table-data
          persistentVolumeClaim:
            claimName: mongodb-table-data
        - name: mongo-table-data-config
          persistentVolumeClaim:
            claimName: mongo-table-data-config
status: {}
