apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\eigenaar\Documents\kompose.exe convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-waiter
  name: mongo-waiter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo-waiter
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\eigenaar\Documents\kompose.exe convert
        kompose.service.type: LoadBalancer
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: mongo-waiter
    spec:
      containers:
        - image: mongo:latest
          name: mongo-waiter
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-waiter-data
      restartPolicy: Always
      volumes:
        - name: mongodb-waiter-data
          persistentVolumeClaim:
            claimName: mongodb-waiter-data
status: {}
