apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\eigenaar\Documents\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql-visit
  name: mysql-visit
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    io.kompose.service: mysql-visit
status:
  loadBalancer: {}
