apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\eigenaar\Documents\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql-visit
  name: mysql-visit
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql-visit
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\eigenaar\Documents\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: mysql-visit
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: abc123
          image: mysql:latest
          name: mysql-visit
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-visit-data
      restartPolicy: Always
      volumes:
        - name: mysql-visit-data
          persistentVolumeClaim:
            claimName: mysql-visit-data
status: {}
