apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\eigenaar\Documents\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: visit-service
  name: visit-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: visit-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\eigenaar\Documents\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: visit-service
    spec:
      containers:
        - env:
            - name: DISH_SERVICE_BASEURL
              value: dish-service:8081
            - name: MYSQL_DB_HOST
              value: mysql-visit
            - name: MYSQL_DB_PASSWORD
              value: abc123
            - name: MYSQL_DB_PORT
              value: "3306"
            - name: MYSQL_DB_USERNAME
              value: root
            - name: TABLE_SERVICE_BASEURL
              value: table-service:8082
            - name: WAITER_SERVICE_BASEURL
              value: waiter-service:8083
          image: jetzel/visit-service
          name: visit-service
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
