apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\eigenaar\Documents\kompose.exe convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: waiter-service-tcp
  name: waiter-service-tcp
spec:
  ports:
    - name: "27018"
      port: 27018
      targetPort: 27018
  selector:
    io.kompose.service: waiter-service
  type: LoadBalancer
status:
  loadBalancer: {}
