apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\eigenaar\Documents\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: waiter-service
  name: waiter-service
spec:
  ports:
    - name: "27021"
      port: 27021
      targetPort: 27017
  selector:
    io.kompose.service: waiter-service
status:
  loadBalancer: {}
