server:
  port: 8084

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  cloud:
    gateway:
      routes:
        - id: visit-service
          uri: http://${VISIT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/visits
          filters:
            - SetPath=/api/visit
        - id: table-service
          uri: http://${TABLE_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/tables
          filters:
            - SetPath=/api/table
        - id: dish-service
          uri: http://${DISH_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/dishes
          filters:
            - SetPath=/api/dish
        - id: waiter-service
          uri: http://${WAITER_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/waiters
          filters:
            - SetPath=/api/waiter

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENDID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs