server:
  port: 8084

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE
    org.springframework.security: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: table-service-all
          uri: http://${TABLE_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/tables
            - Method=GET
          filters:
            - SetPath=/api/table/all
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 3
        - id: table-service-post
          uri: http://${TABLE_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/tables
            - Method=POST
          filters:
            - SetPath=/api/table
        - id: table-service-put
          uri: http://${TABLE_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/tables/{id}
            - Method=PUT
          filters:
            - SetPath=/api/table/tables/{id}
        - id: table-service-delete
          uri: http://${TABLE_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/tables/{id}
            - Method=DELETE
          filters:
            - SetPath=/api/table/tables/{id}
        - id: dish-service-all
          uri: http://${DISH_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/dishes
            - Method=GET
          filters:
            - SetPath=/api/dish/all
        - id: waiter-service-all
          uri: http://${WAITER_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/waiters
            - Method=GET
          filters:
            - SetPath=/api/waiter/all

